generator: Don't care android.SourceDepTag
 * android.SourceDepTag is deprecated.

Error: vendor/crystal/build/soong/generator/generator.go:150:17: undefined: android.SourceDepTag.

Signed-off-by: Kujou Yuko <i@779.moe>
Change-Id: Idf9709f67848a9b704919eee1273f05d6ac9dfb8